apiVersion: v1
kind: Service
metadata:
  name: attendance-assistant-service
spec:
  type: NodePort
  selector:
    app: attendance-assistant
  ports:
    - port: 7860
      targetPort: 7860
      nodePort: 31760  # Pick an unused port
